# 컬러 영상 다루기

In [16]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

## 컬러 영상의 픽셀값 참조

In [3]:
src = cv2.imread("./data/butterfly.jpg", cv2.IMREAD_COLOR)
src.shape, src.dtype

((356, 493, 3), dtype('uint8'))

In [5]:
# 좌상단 (0,0) 좌표의 각 b, g, r의 픽셀값(광도)을 출력해보기

b = src[0][0][0]
g = src[0][0][1]
r = src[0][0][2]
b, g, r

(47, 88, 50)

- (참고)

In [9]:
# matplotlib의 default backend
%matplotlib inline
plt.imshow(src)

In [11]:
# matplotlib의 backend로 qt 사용시 픽셀의 RGB값 표시됨
%matplotlib qt

import matplotlib.image as mpimg
import matplotlib.pyplot as plt

plt.imshow(src)

## 컬러 영상의 픽셀값 반전

In [19]:
src = cv2.imread("./data/butterfly.jpg", cv2.IMREAD_COLOR)

# option 1. 전체 이미지 반전
dst = 255 - src[:,:,:3] 

# option 2. 채널별 이미지 반전
# dst[:, :, 0] = 255 - src[:,:,0]
# dst[:, :, 1] = 255 - src[:,:,1]
# dst[:, :, 2] = 255 - src[:,:,2]


cv2.imshow("src", src)
cv2.imshow("dst", dst)
cv2.waitKey()
cv2.destroyAllWindows()

## 색공간 변환

In [20]:
src = cv2.imread("./data/butterfly.jpg", cv2.IMREAD_COLOR)

# BGR2GRAY로 변환후 gray 이미지 표시
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

cv2.imshow("src", src)
cv2.imshow("gray", gray)
cv2.waitKey()
cv2.destroyAllWindows()

## 색상 채널 나누기

In [32]:
src = cv2.imread("./data/butterfly.jpg", cv2.IMREAD_COLOR)

# BGR2HSV로 변환후, h, s, v 채널을 각각 윈도우에 표시
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(hsv)

cv2.imshow("src", src)
cv2.imshow("h", h)
cv2.imshow("s", s)
cv2.imshow("v", v)
cv2.waitKey()
cv2.destroyAllWindows()

In [33]:
src = cv2.imread("./data/butterfly.jpg", cv2.IMREAD_COLOR)
# BGR2YCrCb로 변환후, y, cr, cb 채널을 각각 윈도우에 표시
# gray scale로도 변환하여 픽셀 밝기값이 ycrcb의 y값과 같은지 확인
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)
ycrcb = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)
y, cr, cb = cv2.split(ycrcb)

cv2.imshow("src", src)
cv2.imshow("y", y)
cv2.imshow("cr", cr)
cv2.imshow("cb", cb)
cv2.waitKey()
cv2.destroyAllWindows()

In [34]:
print((y == gray).sum(), (y != gray).sum()) # 거의 같음

print(gray.shape)

print(356*493)

175502 6
(356, 493)
175508


In [35]:
src = cv2.imread("./data/candies.png", cv2.IMREAD_COLOR)

# b, g, r로 channel split 후 채널마다 윈도우에 표시
b, g, r = cv2.split(src)

cv2.imshow('src', src)
cv2.imshow('b', b)
cv2.imshow('g', g)
cv2.imshow('r', r)
cv2.waitKey()
cv2.destroyAllWindows()

# 컬러 영상 처리 기법

## 컬러 히스토그램 평활화

In [36]:
# 명암비를 조정한다는것은 "밝기"값하고만 상관이 있음
src = cv2.imread("./data/pepper.bmp")
src_yCrCb = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb) # YCrCb : Y(밝기 정보), Cr(붉은색 색상정보), Cb(푸른색 색상정보)

y, Cr, Cb = cv2.split(src_yCrCb)

y_equalized = cv2.equalizeHist(y) # 밝기 정보만을 담고 있는 y 채널에 대해서만 평활화를 수행

dst_yCrCb = cv2.merge([y_equalized, Cr, Cb])

dst = cv2.cvtColor(dst_yCrCb, cv2.COLOR_YCrCb2BGR)

cv2.imshow("src", src)
cv2.imshow("dst", dst)
cv2.waitKey()
cv2.destroyAllWindows()


## 색상 범위 지정에 의한 영역 분할

In [ ]:
src = cv2.imread("./data/hand.jpg")
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)

# picker tool 기준 살색의 hsv값
# h : 21 (0~360)
# s : 38 (0~100)
# v : 66 (0~100)

# opencv 기준 hsv 값으로 대략 바꾸면
# h : 10~11 (0~179)
# s : 90~110 (0~255)
# v : 165 (0~255)

lowerb = (0, 20, 0)
upperb = (20, 160, 255)
dst = cv2.inRange(hsv, lowerb, upperb) # dst : lowerb~upperb(흰색), 그외(검은색)


cv2.imshow("src", src)
cv2.imshow("dst", dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [46]:
def on_level_change(pos) :
    lower_h = cv2.getTrackbarPos('Lower H', 'dst')
    upper_h = cv2.getTrackbarPos('Upper H', 'dst')
    lower_s = cv2.getTrackbarPos('Lower S', 'dst')
    upper_s = cv2.getTrackbarPos('Upper S', 'dst')
    lowerb = (lower_h, lower_s, 0)
    upperb = (upper_h, upper_s, 255)
    dst = cv2.inRange(hsv, lowerb, upperb)
    cv2.imshow('dst', dst)

src = cv2.imread("./data/candies.png")
hsv = cv2.cvtColor(src, cv2.COLOR_BGR2HSV)
h, s, v = cv2.split(hsv)
cv2.imshow('src', src)
cv2.namedWindow('dst')

cv2.createTrackbar('Lower H', 'dst', 0, 255, on_level_change)
cv2.createTrackbar('Upper H', 'dst', 0, 255, on_level_change)
cv2.createTrackbar('Lower S', 'dst', 0, 255, on_level_change)
cv2.createTrackbar('Upper S', 'dst', 0, 255, on_level_change)
cv2.setTrackbarPos('Lower H', 'dst', 0)
cv2.setTrackbarPos('Upper H', 'dst', 180)
cv2.setTrackbarPos('Lower S', 'dst', 0)
cv2.setTrackbarPos('Upper S', 'dst', 200)

cv2.waitKey()
cv2.destroyAllWindows()

## 히스토그램 역투영

In [48]:
src = np.array([[0, 0, 0, 0],
                [1, 1, 3, 5],
                [6, 1, 1, 3],
                [4, 3, 1, 7]], dtype=np.uint8)

hist = cv2.calcHist(images = [src], channels=[0], mask=None, histSize=[4], ranges=[0, 8])
hist

array([[9.],
       [3.],
       [2.],
       [2.]], dtype=float32)

In [49]:
backP = cv2.calcBackProject([src], [0], hist, [0, 8], scale=1)
backP

array([[9, 9, 9, 9],
       [9, 9, 3, 2],
       [2, 9, 9, 3],
       [2, 3, 9, 2]], dtype=uint8)

In [52]:
ref = cv2.imread("./data/ref.png", cv2.IMREAD_COLOR)
mask = cv2.imread("./data/mask.bmp", cv2.IMREAD_GRAYSCALE)

ref_yrcrcb = cv2.cvtColor(ref, cv2.COLOR_BGR2YCrCb)

channels = [1, 2] # cr, cb channel
histSize = [128, 128] # cr의 histSize, cb의 histSize
ranges = [0, 256] + [0, 256]

hist = cv2.calcHist(images=[ref_yrcrcb], channels=channels, mask=mask, histSize=histSize, ranges=ranges)

src = cv2.imread("./data/kids.png", cv2.IMREAD_COLOR)
src_ycrcb = cv2.cvtColor(src, cv2.COLOR_BGR2YCrCb)


back_proj = cv2.calcBackProject([src_ycrcb], channels, hist, ranges, 1)

cv2.imshow("ref", ref)
cv2.imshow("mask", mask)
cv2.imshow("back_proj", back_proj)

cv2.waitKey()
cv2.destroyAllWindows()

In [55]:
hist

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [56]:
back_proj

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 1, 0]], dtype=uint8)

# 영상의 이진화

## 전역 이진화

- Trackbar 이용

In [57]:
def on_threshold(pos):
    _, dst = cv2.threshold(src, pos, 255, cv2.THRESH_BINARY)
    cv2.imshow("dst", dst)
    
src = cv2.imread("./data/neutrophils.png", cv2.IMREAD_GRAYSCALE)

cv2.imshow("src", src)
cv2.imshow("dst", dst)

cv2.createTrackbar("threhold", "dst", 0, 255, on_threshold)
cv2.setTrackbarPos("threhold", "dst", 128)
cv2.waitKey()
cv2.destroyAllWindows()

- Otsu 알고리즘에 의한 임계값 사용

In [62]:
src = cv2.imread("./data/neutrophils.png", cv2.IMREAD_GRAYSCALE)

thresh, dst = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

print("thresh : ",thresh)

cv2.imshow("src", src)
cv2.imshow("dst", dst)


cv2.waitKey()
cv2.destroyAllWindows()

thresh :  206.0


- Otsu 알고리즘에 의한 임계값 사용

In [63]:
src = cv2.imread("./data/heart10.jpg", cv2.IMREAD_GRAYSCALE)

thresh, dst = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

print("thresh : ",thresh)

cv2.imshow("src", src)
cv2.imshow("dst", dst)


cv2.waitKey()
cv2.destroyAllWindows()

thresh :  175.0


## 적응형 이진화

In [70]:
# 불균형한 조명의 이미지는 전역 이진화가 잘되지 않음
src = cv2.imread("./data/sudoku.jpg", cv2.IMREAD_GRAYSCALE)

thresh, dst = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

print("thresh : ",thresh)
cv2.imshow("src", src)
cv2.imshow("dst", dst)


cv2.waitKey()
cv2.destroyAllWindows()

thresh :  97.0


In [83]:
def on_trackbar(pos):
    bsize = pos
    
    if bsize % 2== 0: # 짝수
        bsize = bsize+1
        
    if bsize < 3:
        bsize = 3
        
    dst = cv2.adaptiveThreshold(src, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY, bsize, 5)
    cv2.imshow("dst", dst)

src = cv2.imread("./data/sudoku.jpg", cv2.IMREAD_GRAYSCALE)

cv2.imshow("src", src)
cv2.namedWindow("dst")

cv2.createTrackbar("block size", "dst", 0, 200, on_trackbar)
cv2.setTrackbarPos("block size", "dst", 11)

cv2.waitKey()
cv2.destroyAllWindows()

# 모폴로지 연산

## 침식과 팽창

In [86]:
src = cv2.imread("./data/milkdrop.bmp", cv2.IMREAD_GRAYSCALE)

thresh, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

erode = cv2.erode(src_bin, None)
dilate = cv2.dilate(src_bin, None)


cv2.imshow("src", src)
cv2.imshow("src_bin", src_bin)
cv2.imshow("erode", erode)
cv2.imshow("dilate", dilate)

cv2.waitKey()
cv2.destroyAllWindows()

## 열기와 닫기

In [88]:
src = cv2.imread("./data/milkdrop.bmp", cv2.IMREAD_GRAYSCALE)

thresh, src_bin = cv2.threshold(src, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

# 열기 : 침식 -> 팽창
opening = cv2.morphologyEx(src_bin, cv2.MORPH_OPEN, None, iterations=1)

# 닫기 : 팽창 -> 침식
closing = cv2.morphologyEx(src_bin, cv2.MORPH_CLOSE, None, iterations=1)


cv2.imshow("src_bin", src_bin)
cv2.imshow("opening", opening)
cv2.imshow("closing", closing)

cv2.waitKey()
cv2.destroyAllWindows()


# 레이블링과 외곽선 검출

In [95]:
src = np.array([[0, 0, 1, 1, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 0],
                [0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 1, 0, 0, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0]]).astype(np.uint8)


src = src * 255

cnt, labels = cv2.connectedComponents(src) # 배경:0, 객체: 0이 아님

print(cnt)
print(labels)

4
[[0 0 1 1 0 0 0 0]
 [1 1 1 1 0 0 2 0]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 0 3 3 0]
 [0 0 0 3 3 3 3 0]
 [0 0 0 3 0 0 3 0]
 [0 0 3 3 3 3 3 0]
 [0 0 0 0 0 0 0 0]]


- circles.jpg에 있는 원(객체)을 서로 다른 색으로 표시하기

In [112]:
src = cv2.imread("./data/circles.jpg")
gray = cv2.cvtColor(src, cv2.COLOR_BGR2GRAY)

thresh, src_bin = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)

cnt, labels = cv2.connectedComponents(src_bin)

dst = np.zeros(src.shape,src.dtype) # 객체별로 색깔을 표시할 array (3차원)

for i in range(1, cnt): # 객체 1, 2, 3     
    b = np.random.randint(0, 256)
    g = np.random.randint(0, 256)
    r = np.random.randint(0, 256)
    dst[labels==i] = [b, g, r]
       
cv2.imshow("gray", gray)
cv2.imshow("src_bin", src_bin)
cv2.imshow("dst", dst)
cv2.waitKey()
cv2.destroyAllWindows()